general {
    no_fade_in = false
    grace = 0
}

background {
    monitor =
    path = /home/aman/wallpapers
    blur_passes = 3
    blur_size = 8
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgb(203, 166, 247)
    inner_color = rgb(30, 30, 46)
    font_color = rgb(205, 214, 244)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    rounding = 15
    check_color = rgb(166, 227, 161)
    fail_color = rgb(243, 139, 168)
    fail_text = <i>Incorrect Password</i>
    fail_transition = 300

    position = 0, -80
    halign = center
    valign = center
}

# Logo
image {
    monitor =
    path = /home/aman/.config/hypr/logo.png
    size = 300
    border_size = 0
    position = 0, 150
    halign = center
    valign = center
}
